// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqNf_saN57ijZJF_5GfPj6N2RYl_Kf1rk',
    appId: '1:239385068121:web:90430c504bb3082f606748',
    messagingSenderId: '239385068121',
    projectId: 'fireout-svelte',
    authDomain: 'fireout-svelte.firebaseapp.com',
    storageBucket: 'fireout-svelte.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqNf_saN57ijZJF_5GfPj6N2RYl_Kf1rk',
    appId: '1:239385068121:android:90430c504bb3082f606748',
    messagingSenderId: '239385068121',
    projectId: 'fireout-svelte',
    storageBucket: 'fireout-svelte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqNf_saN57ijZJF_5GfPj6N2RYl_Kf1rk',
    appId: '1:239385068121:ios:90430c504bb3082f606748',
    messagingSenderId: '239385068121',
    projectId: 'fireout-svelte',
    storageBucket: 'fireout-svelte.firebasestorage.app',
    iosBundleId: 'com.example.fireout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqNf_saN57ijZJF_5GfPj6N2RYl_Kf1rk',
    appId: '1:239385068121:macos:90430c504bb3082f606748',
    messagingSenderId: '239385068121',
    projectId: 'fireout-svelte',
    storageBucket: 'fireout-svelte.firebasestorage.app',
    iosBundleId: 'com.example.fireout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqNf_saN57ijZJF_5GfPj6N2RYl_Kf1rk',
    appId: '1:239385068121:windows:90430c504bb3082f606748',
    messagingSenderId: '239385068121',
    projectId: 'fireout-svelte',
    authDomain: 'fireout-svelte.firebaseapp.com',
    storageBucket: 'fireout-svelte.firebasestorage.app',
  );
}